name: Revive-frontend

on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

jobs: 
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:     
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEPLOY_HOST_STAGING }}
        username: ${{ secrets.DEPLOY_USERNAME_STAGING }}
        port: 22
        key: ${{ secrets.DEPLOY_PASSWORD_STAGING }}
        script: 'sh /home/ubuntu/app-cost.sh'
